apiVersion: v1
kind: Secret
metadata:
  name: rzex-secrets
  namespace: rzex
type: Opaque
stringData:
  # Replace these with actual values in production
  jwt-secret: "CHANGE_ME_TO_STRONG_SECRET"
  postgres-host: "postgres.rzex.svc.cluster.local"
  postgres-password: "CHANGE_ME"
  postgres-user: "rzex"
  postgres-db: "rzex"
  redis-host: "redis.rzex.svc.cluster.local"
  mongo-uri: "mongodb://rzex:CHANGE_ME@mongo.rzex.svc.cluster.local:27017/rzex_market?authSource=admin"
  grafana-password: "CHANGE_ME"
